$schema: https://www.getbifrost.ai/schema
providers:
  mock:
    keys:
      - name: mock-key
        value: dummy
        models:
          - "*"
        weight: 1.0
    network_config:
      base_url: http://127.0.0.1:9000
      default_request_timeout_in_seconds: 60
    custom_provider_config:
      base_provider_type: openai
      allowed_requests:
        chat_completion: true
        chat_completion_stream: true
config_store:
  enabled: false
