TURNS = [
    {"index": 1, "prompt": "Load the project instructions.", "context_tokens": 512, "tool": True},
    {"index": 2, "prompt": "List the files needed for the task.", "context_tokens": 768, "tool": True},
    {"index": 3, "prompt": "Inspect the build configuration.", "context_tokens": 1024, "tool": False},
    {"index": 4, "prompt": "Find the relevant symbols.", "context_tokens": 1536, "tool": True},
    {"index": 5, "prompt": "Read the implementation and tests.", "context_tokens": 2048, "tool": True},
    {"index": 6, "prompt": "Search for similar code.", "context_tokens": 2560, "tool": False},
    {"index": 7, "prompt": "Plan the patch in concrete steps.", "context_tokens": 3072, "tool": True},
    {"index": 8, "prompt": "Implement the first step.", "context_tokens": 3584, "tool": True},
    {"index": 9, "prompt": "Inspect the resulting diff.", "context_tokens": 4096, "tool": False},
    {"index": 10, "prompt": "Implement the second step.", "context_tokens": 4608, "tool": True},
    {"index": 11, "prompt": "Compile the changed target.", "context_tokens": 5120, "tool": True},
    {"index": 12, "prompt": "Fix the compiler diagnostic.", "context_tokens": 5632, "tool": False},
    {"index": 13, "prompt": "Run targeted tests.", "context_tokens": 6144, "tool": True},
    {"index": 14, "prompt": "Inspect test output.", "context_tokens": 6656, "tool": True},
    {"index": 15, "prompt": "Add missing test coverage.", "context_tokens": 7168, "tool": False},
    {"index": 16, "prompt": "Run the formatter.", "context_tokens": 7680, "tool": True},
    {"index": 17, "prompt": "Run static analysis.", "context_tokens": 8192, "tool": True},
    {"index": 18, "prompt": "Resolve the lint finding.", "context_tokens": 8704, "tool": False},
    {"index": 19, "prompt": "Re-run compilation and tests.", "context_tokens": 9216, "tool": True},
    {"index": 20, "prompt": "Inspect all modified files.", "context_tokens": 10240, "tool": True},
    {"index": 21, "prompt": "Check API compatibility.", "context_tokens": 11776, "tool": False},
    {"index": 22, "prompt": "Validate the integration path.", "context_tokens": 13312, "tool": True},
    {"index": 23, "prompt": "Run the full package tests.", "context_tokens": 14848, "tool": True},
    {"index": 24, "prompt": "Review failures and regressions.", "context_tokens": 16384, "tool": False},
    {"index": 25, "prompt": "Apply the final correction.", "context_tokens": 17920, "tool": True},
    {"index": 26, "prompt": "Re-run the full checks.", "context_tokens": 19456, "tool": True},
    {"index": 27, "prompt": "Inspect the final diff.", "context_tokens": 20992, "tool": False},
    {"index": 28, "prompt": "Summarize the implementation.", "context_tokens": 22528, "tool": True},
    {"index": 29, "prompt": "State the verification evidence.", "context_tokens": 24064, "tool": True},
    {"index": 30, "prompt": "Provide the final concise report.", "context_tokens": 25600, "tool": False},
]
